USE RENTIT_DATABASE;
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("AUTO","Autotomobiles-Vehicles");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("APPL","Appliances");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("CLOT","Clothing-Accessories");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("FURN","Furniture");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("GAME","Games-Movies");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("HOBB","Hobbies");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("HOUS","Houses-Rooms-Apartments");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("INST","Instruments");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("OTHE","Other");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("OUTD","Outdoors");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("SERV","Services");
INSERT INTO  CATEGORY (CATEGORY_ID,CATEGORY_NAME) VALUES ("TOOL","Tools");






     
    